In [1]:
import numpy as np

###1.Airthmetic

In [15]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[40,50,60]])

print(a)
print(b)

#Addition
print('-'*20)
print(a+5)
print('*'*10)
print(a+b)

#Subtraction
print('-'*20)
print(a-2)
print('*'*10)
print(a-b)
print('*'*10)
print(b-a)

#Multiplication
print('-'*20)
print(a*2)
print('*'*10)
print(a*b)

#Division
print('-'*20)
print(a /2)
print('*'*10)
print(a/b)

#Exponential
print('-'*20)
print(a**2)
print('*'*10)
print(a**b)

#Modulo
print('-'*20)
print(a%2)
print('*'*10)
print(a%b)

[1 2 3]
[[10 20 30]
 [40 50 60]]
--------------------
[6 7 8]
**********
[[11 22 33]
 [41 52 63]]
--------------------
[-1  0  1]
**********
[[ -9 -18 -27]
 [-39 -48 -57]]
**********
[[ 9 18 27]
 [39 48 57]]
--------------------
[2 4 6]
**********
[[ 10  40  90]
 [ 40 100 180]]
--------------------
[0.5 1.  1.5]
**********
[[0.1   0.1   0.1  ]
 [0.025 0.04  0.05 ]]
--------------------
[1 4 9]
**********
[[                   1              1048576      205891132094649]
 [                   1     1125899906842624 -3535985420588157519]]
--------------------
[1 0 1]
**********
[[1 2 3]
 [1 2 3]]


###2.Comparision

In [20]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print('-'*20)
#>
print(a>b)
print('-'*20)
#<
print(a<b)
print('-'*20)
#>=
print(a>=b)
print('-'*20)
#<=
print(a<=b)
print('-'*20)
#!=
print(a!=b)
print('-'*20)
#==
print(a==b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
--------------------
[[False False False]
 [False False False]]
--------------------
[[False False False]
 [ True  True  True]]
--------------------
[[ True  True  True]
 [False False False]]
--------------------
[[ True  True  True]
 [ True  True  True]]
--------------------
[[False False False]
 [ True  True  True]]
--------------------
[[ True  True  True]
 [False False False]]


###3.Logical

In [22]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print('-'*20)
print(a & b)
print('-'*20)
print(a | b)
print('-'*20)
print(~a)
print('-'*20)
print(~b)
print('-'*20)
print(a ^ b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
--------------------
[[1 2 3]
 [0 0 2]]
--------------------
[[1 2 3]
 [5 7 7]]
--------------------
[-2 -3 -4]
--------------------
[[-2 -3 -4]
 [-5 -6 -7]]
--------------------
[[0 0 0]
 [5 7 5]]


###4.Bitwise

In [24]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print('-'*20)
print(np.bitwise_and(a,b))
print('-'*20)
print(np.bitwise_or(a,b))
print('-'*20)
print(np.bitwise_xor(a,b))
print('-'*20)
print(np.bitwise_not(a,b))
print('-'*20)
print(np.bitwise_left_shift(a,b))
print('-'*20)
print(np.bitwise_right_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
--------------------
[[1 2 3]
 [0 0 2]]
--------------------
[[1 2 3]
 [5 7 7]]
--------------------
[[0 0 0]
 [5 7 5]]
--------------------
[[-2 -3 -4]
 [-2 -3 -4]]
--------------------
[[0 0 0]
 [0 0 0]]
--------------------
[[0 0 0]
 [0 0 0]]


In [28]:
(np.arange(0,100,2)>50).tolist().count(False)

26