In [1]:
import numpy as np

### 1D array

In [6]:
np.random.seed(10)
arr = np.random.randint(1,11,size = 10)
print(arr)

print('*'*30)
print(np.where(arr>5))#gives indiced which satisfy the condition =>0-10,4-10,7-9,8-10,===>indices-Element
print('*'*30)
print(np.where(arr>=5))
print(arr[np.where(arr>=5)])#gives elements in an array
print('*'*30)

[10  5  1  2 10  1  2  9 10  1]
******************************
(array([0, 4, 7, 8]),)
******************************
(array([0, 1, 4, 7, 8]),)
[10  5 10  9 10]


### 2D Array

In [11]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3))
print(arr)

print('*'*30)
indices = np.where(arr>=5)#pairs ==> (0,0),(0,1),(1,1),(2,1),(2,2)
print(indices)
print('*'*30)
print(arr[indices])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
******************************
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2]))
******************************
[10  5 10  9 10]


###3D Array

In [12]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3,3))
print(arr)

print('*'*30)
indices = np.where(arr>=5)#pairs ==> (0,0,0),(0,0,1),(0,1,1),(0,2,1),(0,2,2),(1,0,1)...etc
print(indices)
print('*'*30)
print(arr[indices])

[[[10  5  1]
  [ 2 10  1]
  [ 2  9 10]]

 [[ 1  9  7]
  [ 5  4  1]
  [ 5  7  9]]

 [[ 2  9  5]
  [ 2  4  7]
  [ 6  4 10]]]
******************************
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2]))
******************************
[10  5 10  9 10  9  7  5  5  7  9  9  5  7  6 10]
