In [1]:
import numpy as np

###1.Dot Product

In [23]:
a = np.array([1,2])
b = np.array([2,3])
dot_product = np.dot(a,b)
print(dot_product)

8


In [24]:
c = np.array([1,2,3])
d = np.array([2,3,4])
dot_product = np.dot(c,d)
print(dot_product)

20


In [25]:
#if two vectors do not have same length then we get value error because it do not have same dimensions
x = np.array([1,2])
y = np.array([5,3])
dot_product = np.dot(x,y)
print(dot_product)

11


###2.Matrix Multiplication

In [26]:
#No of columns in a should be equal to no of rows in b then only we can do matrix multiplication otherwise we get error
A = np.array([[1,2],[3,4]])
B = np.array([[2,3],[4,5]])
Matrix_Multiplication = np.matmul(A,B)
print(Matrix_Multiplication)
print('*'*10)
Matrix_Multiplication = np.matmul(B,A)
print(Matrix_Multiplication)

[[10 13]
 [22 29]]
**********
[[11 16]
 [19 28]]


In [27]:
C = np.array([1,2])
D = np.array([[4,1],[3,5]])
Product = np.matmul(C,D)
print(Product)

[10 11]


In [28]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,3],[4,5]])
Product = np.dot(A,B)
print(Product)#Same results as matrix multiplication

[[10 13]
 [22 29]]


###1.Determinant

In [29]:
a = np.array([[1,2], [3,4]])
determinant = np.linalg.det(a)
print(determinant)

-2.0000000000000004


In [30]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
determinant = np.linalg.det(b)
print(determinant)

0.0


###2.Transpose-->Changing Rows into Columns

In [31]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
Transpose = np.transpose(A)
print(Transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [32]:
B = np.array([[1,2,3],[4,5,6]])
Transpose = np.transpose(B)
print(Transpose)

[[1 4]
 [2 5]
 [3 6]]


###3.Inverse of a Matrix-->for only square matrix inverse is possible,-->for determinant zero we cannot find inverse

In [33]:
A = np.array([[1,2], [3,4]])
Inverse = np.linalg.inv(A)
print(Inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


###4.System of Linear Quations --Substitution Method,Elimination Method

In [34]:
a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])
SOLQ = np.linalg.solve(a,b)
print(SOLQ)

[[-4. ]
 [ 4.5]]


In [35]:
a = np.array([[1,2,3],[4,5,6],[7,8,10]])
b = np.array([[10],[11],[12]])
SOLQ = np.linalg.solve(a,b)
print(SOLQ)

[[-9.33333333e+00]
 [ 9.66666667e+00]
 [ 3.55271368e-15]]


###5.Eigen Values and Eigen Vectors-->we find out only for square vectors

In [37]:
A = np.array([[5,4],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print('*'*10)
print(eigenvectors)

[6. 1.]
**********
[[ 0.9701425  -0.70710678]
 [ 0.24253563  0.70710678]]
