In [1]:
import numpy as np

###1.Dot Product

In [3]:
a = np.array([1,2])
b = np.array([2,3])
dot_product = np.dot(a,b)
print(dot_product)

8


In [4]:
c = np.array([1,2,3])
d = np.array([2,3,4])
dot_product = np.dot(c,d)
print(dot_product)

20


In [7]:
#if two vectors do not have same length then we get value error because it do not have same dimensions
x = np.array([1,2])
y = np.array([5,3])
dot_product = np.dot(x,y)
print(dot_product)

11


###2.Matrix Multiplication

In [9]:
#No of columns in a should be equal to no of rows in b then only we can do matrix multiplication otherwise we get error
A = np.array([[1,2],[3,4]])
B = np.array([[2,3],[4,5]])
Matrix_Multiplication = np.matmul(A,B)
print(Matrix_Multiplication)
print('*'*10)
Matrix_Multiplication = np.matmul(B,A)
print(Matrix_Multiplication)

[[10 13]
 [22 29]]
**********
[[11 16]
 [19 28]]


In [10]:
C = np.array([1,2])
D = np.array([[4,1],[3,5]])
Product = np.matmul(C,D)
print(Product)

[10 11]


In [13]:
A = np.array([[1,2],[3,4]])
B = np.array([[2,3],[4,5]])
Product = np.dot(A,B)
print(Product)#Same results as matrix multiplication

[[10 13]
 [22 29]]
