In [2]:
import numpy as np

###1.Saving data in Files

- TextFile

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('textfile.txt',arr,delimiter=',')

- npyFile

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
np.save('data.npy',arr)#Best way to save the File

- csvFile

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.csv',arr,header = 'a,b,c')

- jsonFile

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('file.json',arr,delimiter=',',header = '{"data" : [',footer = ']}')

- yaml

In [12]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('file.yaml',arr,delimiter=',',header = '- data : ')

###2.Reading Data From Files

- TextFile

In [16]:
data = np.loadtxt('textfile.txt',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- npyFile

In [23]:
data = np.load('data.npy')#Best Way
print(data)

[[1 2 3]
 [4 5 6]]


- csvFile

In [20]:
data = np.loadtxt('data.csv')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- jsonFile

In [21]:
data = np.loadtxt('file.json',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- yamlFile

In [22]:
data = np.loadtxt('file.yaml',delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


###3.Writing data in Files

###1.Replacing exisiting Content

In [25]:
data = np.array([4,5,6])
np.savetxt('textfile.txt',data,delimiter=',')#Replaces the values (1,2,3,4,5,6) with 4,5,6

###2.Appending the data on existing File

In [26]:
data = np.load('data.npy')

data = np.append(data,[[7,8,9]],axis=0)
np.save('data.npy',data)

In [27]:
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
