###1.Dealing With Null Values

In [1]:
import numpy as np

- None to np.nan

In [2]:
arr = np.array([1,2,3,None,4,5,None])

print(arr)

arr[arr == None] = np.nan
print(arr)

[1 2 3 None 4 5 None]
[1 2 3 nan 4 5 nan]


- Checking the Null Values

In [3]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)
print(np.isnan(arr))

[ 1.  2.  3. nan  4.  5. nan]
[False False False  True False False  True]


- Removing the Null Values

In [4]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(np.isnan(arr)) #Print the True where there is null values
print('*'*20)
print(arr[~np.isnan(arr)]) #Print the array without null values
print('*'*20)
print(arr[np.isnan(arr)])#Print the null values only
print('*'*20)
print(~np.isnan(arr))#Prints the negation of the values true becomes false,false becomes true

[False False False  True False False  True]
********************
[1. 2. 3. 4. 5.]
********************
[nan nan]
********************
[ True  True  True False  True  True False]


- Filling Null with Fixed Values

In [5]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)
print('*'*20)
arr[np.isnan(arr)] = 0
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
********************
[1. 2. 3. 0. 4. 5. 0.]


- Filling the Null With Avergae

In [6]:
arr = np.array([1,2,3,np.nan,4,5,np.nan])
print(arr)
print('*'*20)
print(np.mean(arr))#avergae of the array -->we get avergae value as nan because when we add anything nan we get avergae as nan only
print('*'*20)
print(np.nanmean(arr))#the avergae value
print('*'*20)
arr[np.isnan(arr)] = np.nanmean(arr)#the null values is replaced by average values
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
********************
nan
********************
3.0
********************
[1. 2. 3. 3. 4. 5. 3.]


###2.Filtering and Aggregating with Numpy

**Filtering**

In [21]:
arr  = np.random.randint(1,11,size = (5,5))

arr

array([[ 2,  4,  6,  6,  1],
       [10,  7,  2,  8,  6],
       [ 9,  7,  2,  8,  7],
       [ 5,  1,  6,  8,  1],
       [ 1,  2,  8,  1,  2]])

- Filter elements greater than 5

In [22]:
print(arr[arr>5])

[ 6  6 10  7  8  6  9  7  8  7  6  8  8]


- Filter the elements that are even

In [23]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  6, 10,  2,  8,  6,  2,  8,  6,  8,  2,  8,  2])

- Filter the elements that are both greater than 5 and are even

In [24]:
arr[(arr > 5) & (arr %2 == 0)]

array([ 6,  6, 10,  8,  6,  8,  6,  8,  8])

- Filter elements that are divisble by either 3 or 7

In [25]:
arr[(arr % 3 == 0) | (arr % 7 == 0)]

array([6, 6, 7, 6, 9, 7, 7, 6])

- Filter elements based on condition on another array

In [27]:
arr1 = np.array([True,False,True,False,True])

arr[arr1]

array([[2, 4, 6, 6, 1],
       [9, 7, 2, 8, 7],
       [1, 2, 8, 1, 2]])

In [28]:
arr

array([[ 2,  4,  6,  6,  1],
       [10,  7,  2,  8,  6],
       [ 9,  7,  2,  8,  7],
       [ 5,  1,  6,  8,  1],
       [ 1,  2,  8,  1,  2]])

- Filter the elements based on specific row

In [29]:
arr

array([[ 2,  4,  6,  6,  1],
       [10,  7,  2,  8,  6],
       [ 9,  7,  2,  8,  7],
       [ 5,  1,  6,  8,  1],
       [ 1,  2,  8,  1,  2]])

In [33]:
arr[arr[-2,:] > 5]

array([[9, 7, 2, 8, 7],
       [5, 1, 6, 8, 1]])

In [37]:
filtered_array = arr[2][arr[-2,:] > 5]
filtered_array


array([2, 8])

In [38]:
arr[-2, :] > 5

array([False, False,  True,  True, False])

**Aggregate Functions**

- sum

In [43]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

print('*'*20)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr))
print(np.sum(arr,axis = 0))#takes sum columns wise
print(np.sum(arr,axis = 1))#takes sum row wise

print('*'*20)


15
********************
45
[12 15 18]
[ 6 15 24]
********************


- mean

In [48]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))
print('*'*20)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(arr))
print(np.mean(arr,axis = 0))
print(np.mean(arr,axis = 1))

3.0
********************
5.0
[4. 5. 6.]
[2. 5. 8.]


- standard deviation

In [49]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))
print('*'*20)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.std(arr))

1.4142135623730951
********************
2.581988897471611


- min-max

In [53]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))
print('*'*20)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.min(arr))
print(np.min(arr,axis = 0))
print(np.min(arr,axis = 1))

print('-'*30)

arr = np.array([1,2,3,4,5])
print(np.max(arr))
print('*'*20)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.max(arr))
print(np.max(arr,axis = 0))
print(np.max(arr,axis = 1))

1
********************
1
[1 2 3]
[1 4 7]
------------------------------
5
********************
9
[7 8 9]
[3 6 9]


- median

In [54]:
arr = np.array([1,2,3,4,5])
print(np.median(arr))
print('*'*20)
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.median(arr))
print(np.median(arr,axis = 0))
print(np.median(arr,axis = 1))

3.0
********************
5.0
[4. 5. 6.]
[2. 5. 8.]


###3.Descriptive Statistics With Numpy

In [58]:
arr = np.random.randint(low = 1,high = 101,size = 100)
arr

array([ 88,  72,  88,  53,  83,  18,   4,  61,  51,  96,  16,  22,  92,
        40,  44,   7,   8,  31,  76,  17,  12,  13,   6,   9,  80,   3,
        63,  60,  80,  77,  67,  16,  51,   2,  31,  28,  64,  28,  56,
        37,  67,  74,   2,   9,  46,  13,   2, 100,   6,  15,  80,  11,
        97,  38,  41,  70,  32,  69,  32,  56,  16,  64,  30,   6,  76,
        61,  35,  47,  51,  82,  23,  74,  57,  50,  28,   8,   7,  88,
        95,  40, 100,   9,  11,  39,  88,  72,  91,  63,  95,   6,  70,
        22,  65,  60,  80,  28,  84,  30,  15,  56])

In [60]:
mean = np.mean(arr)
print(mean)
print('*'*20)

median = np.median(arr)
print(median)
print('*'*20)

mode = np.argmax(np.bincount(arr))#This function counts the occurrences of each non-negative integer value in the arr array
print(mode)
print('*'*20)

std = np.std(arr)
print(std)
print('*'*20)

var = np.var(arr)
print(var)
print('*'*20)

min = np.min(arr)
print(min)
print('*'*20)

max = np.max(arr)
print(max)

46.32
********************
46.5
********************
6
********************
29.920855602739703
********************
895.2575999999999
********************
2
********************
100


In [61]:
q1 = np.percentile(arr,25)
q2 = np.percentile(arr,50)
q3 = np.percentile(arr,75)

print(q1)
print(q2)
print(q3)

16.0
46.5
72.0


In [62]:
IQR = q3 - q1
print(IQR)

56.0


In [63]:
skewness = np.mean((arr - mean)**3)/ (std ** 3)
print(skewness)

0.09953830364927116


In [64]:
kurtosis = np.mean((arr - mean)**4)/ (std ** 4)
print(kurtosis)

1.701385131970565


###4.Searching and Sorting

**Searching**

In [70]:
arr = np.array([1,3,4,6,5,7,12,13])

#Linear Search
#def linear_search(arr,x):
  #for i in range(len(arr)):
    #if arr[i] == x:
      #return i
  #return -1 ==> this is the code we should write if we want to search if we want to do with numpy let's see

index = np.where(arr == 3)
print(index)

(array([1]),)


In [71]:
#Binary Search
index = np.searchsorted(arr,4)
print(index)


2


In [72]:
#Binary Search with multiple values
index = np.searchsorted(arr, [3,5])
print(index)


[1 3]


In [73]:
#searching the closte value
index = np.argmin(np.abs(arr - 12))
print(index)

6


**Sorting**

In [78]:
arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr)#by default it is using quick sort
print(sorted_arr)
print('*'*20)
#Quick sort
sorted_arr = np.sort(arr, kind = 'quicksort')
print(sorted_arr)
print('*'*20)
#Heap Sort
sorted_arr = np.sort(arr, kind = 'Heapsort')
print(sorted_arr)
print('*'*20)
#Merge Sort
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]
********************
[0 1 2 3 4 5 6 7 8 9]
********************
[0 1 2 3 4 5 6 7 8 9]
********************
[0 1 2 3 4 5 6 7 8 9]


###5.Data Cleaning with Numpy

###1.Masking with Boolean Array

In [79]:
arr = np.array([1,2,np.nan,4,5,np.nan])
arr

array([ 1.,  2., nan,  4.,  5., nan])

In [80]:
np.isnan(arr)

array([False, False,  True, False, False,  True])

In [83]:
print(arr[np.isnan(arr)])

[nan nan]


In [82]:
print(arr[~np.isnan(arr)])

[1. 2. 4. 5.]


###2.Replacing outliers with specific value

In [87]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr[arr>7] = 7
print(arr)
print('*'*20)
arr[arr<3] = 3
print(arr)

[1 2 3 4 5 6 7 7 7]
********************
[3 3 3 4 5 6 7 7 7]


###3.Removing the Duplicates

In [91]:
arr = np.array([1,2,2,3,3,2,4,5,6,7,8,9,3])
print(arr)
print('*'*20)
unique_arr = np.unique(arr)
print(unique_arr)
print('*'*20)
print(set(arr))

[1 2 2 3 3 2 4 5 6 7 8 9 3]
********************
[1 2 3 4 5 6 7 8 9]
********************
{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)}


###4.Categorical data to one hot encoding

In [94]:
categorical_arr = np.array(['A','B,','C','D','E','F'])

numerical_arr = np.array([0,1,2,3,4,5])

print(categorical_arr)
print('*'*30)

one_hot_arr = np.eye(6)[numerical_arr]
print(one_hot_arr)

['A' 'B,' 'C' 'D' 'E' 'F']
******************************
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


###5.Data Normalization

In [98]:
arr = np.array([1,2,3,4,5])

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized_arr)


[0.   0.25 0.5  0.75 1.  ]
