###1.Arrays vs Lists Comparision

In [ ]:
lst = [1,2,3]
print(lst)
print(type(lst))

[1, 2, 3]
<class 'list'>


In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#comparision
print(arr == lst)

[ True  True  True]


In [ ]:
print(arr.tolist() == lst)#array converted to list and compared list with list so both are equal it returned true

True


In [ ]:
lst = [1,3,2]
arr = np.array([1,2,3])

print(lst == arr)
print(sorted(lst) == sorted(arr))

[ True False False]
True


###2.Addding elements in an Array vs List

In [ ]:
lst = [1,3,2]
arr = np.array([1,2,3])
print(lst)
lst.append(2)
print(lst)

print('-----'*5)
print(arr)
arr = np.append(arr,4)
print(arr)

[1, 3, 2]
[1, 3, 2, 2]
-------------------------
[1 2 3]
[1 2 3 4]


###3.Removing elements in an Array vs List

In [ ]:
lst = [1,3,2]
arr = np.array([1,2,3])
print(lst)
lst.pop() #or del lst[-1]--->deleting the last element-using index
print(lst)

print('-----'*5)
print(arr)
arr = np.delete(arr,-2)
print(arr)

[1, 3, 2]
[1, 3]
-------------------------
[1 2 3]
[1 3]


###4.Updating elements in an Array vs List

In [ ]:
lst = [1,3,2]
arr = np.array([1,2,3])

print(lst)
lst[-1] = 5
lst[-3] = 6
print(lst)

print('---'*5)
print(arr)
arr[-1] = 5
arr[-3] = 6
print(arr)

[1, 3, 2]
[6, 3, 5]
---------------
[1 2 3]
[6 2 5]


###5.Comparision between Array vs List

In [ ]:
import time

#creating the data
my_list = list(range(1000000))
my_array = np.arange(1000000)

#search time for list
start_time = time.time()
for i in range(1000):
  if 5000000 in my_list:
    pass
end_time = time.time()
print('List :' ,end_time - start_time)


#search time for array
start_time = time.time()
for i in range(1000):
  if 5000000 in my_array:
    pass
end_time = time.time()
print('Array :',end_time - start_time)

List : 10.873612642288208
Array : 0.477933406829834
