###1.Converting DataStrutures to Numpy Arrays

In [ ]:
import numpy as np

**1.1)Converting a tuple to an array**

In [ ]:
tup = (1,2,3,4,5)
print(tup)
print(type(tup))

arr = np.array(tup)
print(arr)
print(type(arr))


(1, 2, 3, 4, 5)
<class 'tuple'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


**1.2)Converting a list to an array**

In [ ]:
lst = [1,2,3,4,5]
print(lst)
print(type(lst))

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


**1.3)Converting a Dictionary to an array**

In [ ]:
dictionary = {1:'apple',2:'ball',3:'cat'}
print(dictionary)
print(type(dictionary))

arr = np.array(dictionary)
print(arr)
print(type(arr))

print('--'*20)
#Efficient way of converting dictionary into an array is adding key and value pairs separately
arr_keys = np.array(list(dictionary.keys()))
arr_values = np.array(list(dictionary.values()))
print(arr_keys)
print(type(arr_keys))
print(arr_values)
print(type(arr_values))


{1: 'apple', 2: 'ball', 3: 'cat'}
<class 'dict'>
{1: 'apple', 2: 'ball', 3: 'cat'}
<class 'numpy.ndarray'>
----------------------------------------
[1 2 3]
<class 'numpy.ndarray'>
['apple' 'ball' 'cat']
<class 'numpy.ndarray'>


**1.4)Converting a set to an array**

In [ ]:
set_ = {1,2,3,4,5}
print(set_)
print(type(set_))

arr = np.array(set_)
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'set'>
{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


**1.5)Converting String to array**

In [ ]:
#Two ways
arr = np.array('hello world')
print(arr)
print(type(arr))
arr = np.array(list('hello world'))
print(arr)
print(type(arr))

hello world
<class 'numpy.ndarray'>
['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


###2.Converting the Datatype of Numpy Array

**2.1)Create an array of integers**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

arr = arr.astype('float')
print(arr)
print(arr.dtype)

arr = arr.astype('str')
print(arr)
print(arr.dtype)

arr = arr.astype('bool')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
['1.0' '2.0' '3.0' '4.0' '5.0']
<U32
[ True  True  True  True  True]
bool


**2.2)Create an array of floats**

In [ ]:
arr = np.array([1.,2.,3.,4.,5.])
print(arr)
print(arr.dtype)

arr = arr.astype('int')
print(arr)
print(arr.dtype)

arr = arr.astype('str')
print(arr)
print(arr.dtype)

arr = arr.astype('bool')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64
[1 2 3 4 5]
int64
['1' '2' '3' '4' '5']
<U21
[ True  True  True  True  True]
bool


**2.3)Create an array of strings**

In [ ]:
arr = np.array(['1','2','3','4','5'])
print(arr)
print(type(arr))

arr_int = arr.astype('int')
print(arr_int)
print(arr_int.dtype)

arr_float = arr.astype('float')
print(arr_float)
print(arr_float.dtype)

arr_bool = arr.astype('bool')
print(arr_bool)
print(arr_bool.dtype)
#we caannot convert words such 'A' or 'Sam' in to int,float,bool only numbers we can convert

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
[ True  True  True  True  True]
bool


**2.4)Create an array of boolean**

In [ ]:
arr = np.array([True,False,False,False,True])
print(arr)
print(type(arr))

arr_int = arr.astype('int')
print(arr_int)
print(arr_int.dtype)

arr_float = arr.astype('float')
print(arr_float)
print(arr_float.dtype)

arr_string = arr.astype('str')
print(arr_string)
print(arr_string.dtype)

[ True False False False  True]
<class 'numpy.ndarray'>
[1 0 0 0 1]
int64
[1. 0. 0. 0. 1.]
float64
['True' 'False' 'False' 'False' 'True']
<U5
