###1.Creating MultiDimensioanl Arrays

In [ ]:
import numpy as np

**1.1)Create a 2D array from a list of lists**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


**1.2)Create a 3D array from list of lists**

In [ ]:
arr_ = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr_)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


**1.3)Create a 2D array from list of tuples**

In [ ]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


**1.4)Create a 2D array from a list of arrays**

In [ ]:
arr = np.array([np.array([1,2,3]),np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


**1.5)Create a 2D array from list of Strings**

In [ ]:
arr = np.array([['1','2','3'],['4','5','6']])
print(arr)

[['1' '2' '3']
 ['4' '5' '6']]


**1.6)Create a 2D array from list of Dictionaries**

In [ ]:
arr = np.array([{'a':1,'b':2,'c':3},{'a':4,'b':5,'c':6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'a': 4, 'b': 5, 'c': 6}]


###2.Finding Details of an arrays

**2.1)Print the Shape of the Array**

In [ ]:
arr = np.array([[1,3],[4,6],[7,9]])
print(arr.shape)

(3, 2)


**2.2)Print the number of dimensions of the array**

In [ ]:
arr = np.array([[1,3],[4,6],[7,9]])
print(arr.ndim)

2


**2.3)Print the datatype of the array**

In [ ]:
arr = np.array([[1,3],[4,6],[7,9]])
print(arr.dtype)

int64


**2.4)Print the size of the array**

In [ ]:
arr = np.array([[1,3],[4,6],[7,9],[10,12],[13,15]])
print(arr.size)#no of elements in the array

10


**2.5)Print the item size |bytes takeb by each elemenst in the array**

In [ ]:
arr = np.array([[1,3],[4,6],[7,9],[10,12],[13,15]])
print(arr.itemsize)#lenght of one array elements in bytes-->how much byte each particular data elements is storing

8


**2.6)Print the type of the array**

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>
