In [1]:
import numpy as np


###1.Copy Function With list

In [2]:
#Copy Function with Lists:
#In Python lists, assignment operations like lst1 = lst create a reference to the original list rather than a new copy.
#Modifying either the original list or the copied list affects both variables.
#To create an independent copy, we use the copy() method.


lst = [1,2,3,4,5]
print(lst)
lst1 = lst
print(lst1)
print('-'*10)

lst[0] = 5
print(lst)
print(lst1)
print('-'*10)

lst1[0] = 4
print(lst)
print(lst1)

print()
print('*'*20)
print()

lst = [1,2,3,4,5]
print(lst)
lst1 = lst.copy()
print(lst1)
print('-'*10)

lst[0] = 5
print(lst)
print(lst1)
print('-'*10)
lst[0] = 1

lst1[0] = 5
print(lst)
print(lst1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
----------
[4, 2, 3, 4, 5]
[4, 2, 3, 4, 5]

********************

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[1, 2, 3, 4, 5]
[5, 2, 3, 4, 5]


###2)Copy function with arrays

In [3]:
#Copy Function with Arrays:
#Copy Function with NumPy Arrays:
#NumPy arrays exhibit similar behavior with assignment and copying.
#The copy() method is used to create a deep copy of the array, ensuring independence.

import numpy as np
arr = np.array([1,2,3,4,5])
arr_ = arr.copy()
print(arr)
print(arr_)
print('-'*10)

arr[0] = 5
print(arr)
print(arr_)
arr[0] = 1
print('-'*10)

arr_[0] = 5
print(arr)
print(arr_)

[1 2 3 4 5]
[1 2 3 4 5]
----------
[5 2 3 4 5]
[1 2 3 4 5]
----------
[1 2 3 4 5]
[5 2 3 4 5]
