In [ ]:
import numpy as np

###1)Indexing and Slicing with Lists

In [5]:
#Indexing and Slicing in Lists:
#In Python lists, indexing starts at 0, with negative indices representing elements from the end.
#Slicing allows selecting a subset of elements using start, stop, and step parameters.


# Creating a Python list
my_list = [34,52,76,8,2,55,67,89,21]

# Accessing elements using positive and negative indexing
print(my_list[0])
print(my_list[-1])
print(my_list[2])

print('*'*20)

# Slicing the list
print(my_list[1:4])
print(my_list[:3])
print(my_list[3:])
print(my_list[1:-1])
print(my_list[::2])
print(my_list[::-1]) #reverse the list
print(my_list[1:-1:2])

print('*'*20)

# Modifying elements in the list
my_list[0] = 10
print(my_list)

# Deleting an element
del my_list[1]
print(my_list)

print('*'*20)

# Inserting elements at a specific position
my_list[1:1] = [20, 30]
print(my_list)

34
21
76
********************
[52, 76, 8]
[34, 52, 76]
[8, 2, 55, 67, 89, 21]
[52, 76, 8, 2, 55, 67, 89]
[34, 76, 2, 67, 21]
[21, 89, 67, 55, 2, 8, 76, 52, 34]
[52, 8, 55, 89]
********************
[10, 52, 76, 8, 2, 55, 67, 89, 21]
[10, 76, 8, 2, 55, 67, 89, 21]
********************
[10, 20, 30, 76, 8, 2, 55, 67, 89, 21]


###2)Indexing and Slicing with arrays

In [7]:
#Indexing and Slicing in NumPy Arrays:
#NumPy arrays support similar indexing and slicing operations as Python lists.
#Arrays offer additional functionalities like broadcasting, which allows operations on arrays of different shapes.

import numpy as np  # Importing the NumPy library

# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements using positive and negative indexing
print(my_array[0])   # First element (index 0) -> Output: 1
print(my_array[-1])  # Last element (negative index -1) -> Output: 5
print(my_array[2])   # Third element (index 2) -> Output: 3

print('*'*20)

# Slicing the array
print(my_array[1:4])  # Elements from index 1 to 3 (excluding index 4) -> Output: [2, 3, 4]
print(my_array[:3])   # First 3 elements (index 0 to 2) -> Output: [1, 2, 3]
print(my_array[3:])   # Elements from index 3 to the end -> Output: [4, 5]
print(my_array[::2])  # Every second element (step=2) -> Output: [1, 3, 5]
print(my_array[::-1]) # Reversed array (step=-1) -> Output: [5, 4, 3, 2, 1]

print('*'*20)

# Modifying elements in the NumPy array
my_array[0] = 10  # Changing the first element to 10
print(my_array)  # Output: [10, 2, 3, 4, 5]

print('*'*20)

# Deleting an element (but doesn't modify the original array)
np.delete(my_array, 1)  # Deletes element at index 1 (which is 2)
print(my_array)  # Output is still [10, 2, 3, 4, 5] because np.delete() returns a new array

print('*'*20)

# Inserting elements (but doesn't modify the original array)
np.insert(my_array, 1, [20, 30])  # Inserts 20 and 30 at index 1
print(my_array)  # Output is still [10, 2, 3, 4, 5] because np.insert() returns a new array

1
5
3
********************
[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]
********************
[10  2  3  4  5]
********************
[10  2  3  4  5]
********************
[10  2  3  4  5]
