In [64]:
import numpy as np


###1.Creating Zeros

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

###2)Creating Ones

In [69]:
np.ones(3)

array([1., 1., 1.])

In [70]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.ones((3,2),dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [72]:
np.ones((5,3,7),dtype = int)

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

###3)Creating Eye

In [73]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [75]:
np.eye(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

###4)Generating Random Numbers

In [76]:
np.random.rand()#Every tiem we execute this we get random number generated

0.9881320823434064

In [77]:
if (np.random.rand() > 0.5):
  print('Head')
else:
  print('Tail')

Tail


In [78]:
for i in range(10):
  if (np.random.rand() > 0.5):
    print('Head')
  else:
    print('Tail')#randomly it executes --> random number generated --> values ranges from 0 t0 1

Head
Tail
Tail
Tail
Head
Head
Tail
Head
Tail
Tail


In [79]:
#Creating array of ten values
print(np.random.rand(10))#-->one dimensional array

[0.49862791 0.92756243 0.07635668 0.23732635 0.0230868  0.40684608
 0.96124243 0.5559     0.81707324 0.78514952]


In [80]:
#for creating 2 dimensioanl array
print(np.random.rand(3,3))

[[0.52540054 0.54897867 0.45148473]
 [0.21788054 0.70713961 0.94134312]
 [0.03457653 0.83126634 0.07691455]]


In [81]:
#Random numbers in specific range
np.random.randint(10)

5

In [82]:
np.random.randint(10, size = (3,3))

array([[7, 8, 5],
       [2, 5, 8],
       [8, 7, 0]])

In [83]:
np.random.randint(low = 1, high = 7, size = (4,4))

array([[3, 3, 3, 4],
       [1, 3, 2, 6],
       [5, 5, 1, 3],
       [2, 6, 6, 4]])

In [84]:
np.random.randn()

0.8160266403851587

In [85]:
##Uniform Distribution
np.random.uniform()

0.07548641922940891

In [86]:
arr = np.random.randint(low = 1, high = 7, size = (1000))

for i in range(1,7):
  print(i,arr.tolist().count(i))

1 172
2 176
3 168
4 157
5 154
6 173


#Probability of getting the values in a dice if we roll two dices
#2 - (1,1)
#3 - (1,2) , (2,1)
#4 - (1,3) , (2,2) , (3,1)
#5 - (1,4) , (2,3) , (3,2) , (4,1)
#6 - (1,5) , (2,4) , (3,3) , (4,2) , (5,1)
#7 - (1,6) , (2,5) , (3,4) , (4,3) , (5,2)
#8 - (2,6) , (3,5) , (4,4) , (5,3) , (6,2)
#9 - (3,6) , (4,5) , (5,4) , (6,3)
#10 - (4,6) , (5,5) , (6,4)
#11 - (6,5) , (5,6)
#12 - (6,6) ## - > we get the bell shape graph --> normal distribution

In [87]:
import numpy as np
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

print(np.random.randint(100))
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn())

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace

0.38930100312860916
[0.13652315 0.01104316 0.44195051 0.53532437 0.24877687 0.18916681
 0.09656499 0.71656106 0.48688283 0.08075425]
[[0.84773323 0.85222216 0.02948336]
 [0.49022172 0.06972912 0.13793512]
 [0.94469436 0.980395   0.22265557]]
28
[ 3 70 35 25  1 24 20 38 58  1]
[[81 82 84]
 [92 37 78]
 [60 27 60]]
[[186 192 119]
 [185 154 189]
 [145 148 163]]
0.5749262170845395
[[0.90967654 0.51161858 0.97969813]
 [0.09011265 0.99320405 0.94429675]
 [0.75492331 0.94552509 0.68749053]]
[[5 6 4]
 [4 3 4]
 [5 6 4]]
