In [1]:
import numpy as np

In [11]:
print(np.random.rand())
print('-'*20)
print(np.random.rand(3))
print('-'*20)
print(np.random.randint(10))
print('-'*20)
print(np.random.randint(10, size=(3,5)))

0.5133824385321689
--------------------
[0.45600218 0.20477772 0.03378668]
--------------------
3
--------------------
[[2 6 8 9 3]
 [1 5 0 7 1]
 [9 0 9 1 3]]


In [13]:
#To get / remain the random value as same we use seed --> we wil not get everytime new value if we use seed
np.random.seed(2)

print(np.random.rand())
print('-'*20)
print(np.random.rand(3))
print('-'*20)
print(np.random.randint(10))
print('-'*20)
print(np.random.randint(10, size=(3,5)))

********************
0.43599490214200376
--------------------
[0.02592623 0.54966248 0.43532239]
--------------------
8
--------------------
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [15]:
np.random.seed(2)

print(np.random.rand())
print('-'*20)
print(np.random.rand(3))
print('-'*20)
print(np.random.randint(10))
print('-'*20)
print(np.random.randint(10, size=(3,5)))#=>we can see that for above code and now for the code we get the same value as before because we have used seed

0.43599490214200376
--------------------
[0.02592623 0.54966248 0.43532239]
--------------------
8
--------------------
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [26]:
np.random.seed(3)

arr = np.random.randint(2, size = 1000)

print('Heads:',np.sum(arr == 1))
print('Tails:',np.sum(arr == 0))

Heads: 476
Tails: 524


In [35]:
np.random.seed(5)
for i in range(10):
    arr = np.random.randint(2, size = 1000)

    print('Heads:',np.sum(arr == 1) ,"==>", 'Tails:',np.sum(arr == 0)) # for ten iterations we get like this


Heads: 505 ==> Tails: 495
Heads: 509 ==> Tails: 491
Heads: 481 ==> Tails: 519
Heads: 508 ==> Tails: 492
Heads: 510 ==> Tails: 490
Heads: 490 ==> Tails: 510
Heads: 503 ==> Tails: 497
Heads: 475 ==> Tails: 525
Heads: 496 ==> Tails: 504
Heads: 499 ==> Tails: 501
