In [1]:
import numpy as np

###1.Range

In [11]:
r = range(10)
print(r)

r = range(0,10,2)
print(r)

r = range(10,0,-2)
print(r)

print(5 in r)
print(6 in range(10))
print(list(r))
print(list(range(10)))


range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
False
True
[10, 8, 6, 4, 2]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


###2.arange

In [8]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [9]:
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


In [12]:
print(np.arange(0,10,.5))#=>this we cannot do it in range function

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


###3.linspace==>equal intervals we create the numbers

In [17]:
l = np.linspace(0,10,5)#it will give five equal steps between the given range
print(l)

[ 0.   2.5  5.   7.5 10. ]


In [18]:
l = np.arange(0,16,5)
print(l)

[ 0  5 10 15]


In [22]:
l = np.linspace(1,10,9)
print(l)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [23]:
l = np.linspace(1,10,9,endpoint= False)
print(l)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [25]:
l = np.linspace(1,10,9,retstep = True)#=>retstep = gives what step we are taking
print(l)

(array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ]), np.float64(1.125))


In [26]:
l,s = np.linspace(1,10,9,retstep = True)#=>retstep = gives what step we are taking
print(l)
print(s)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
1.125


###4.logspcae

In [27]:
arr = np.logspace(0,10,5)
print(arr)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


In [28]:
arr = np.logspace(0,10,5,endpoint = False)
print(arr)

[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]


In [29]:
arr = np.logspace(0,10,5,base = 2)
print(arr)

[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]
