###1.Flattening

In [15]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print('*'*10)
flatten_arr = arr.flatten()
print(flatten_arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
**********
[1 2 3 4 5 6]
(2, 3)


In [17]:
arr = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(arr)
print(arr.shape)
print('*'*10)
flatten_arr = arr.flatten()
print(flatten_arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]
(2, 2, 2)
**********
[1 2 3 4 4 5 5 6]
(2, 2, 2)


###2.Reshaping

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print('*'*10)

reshaped_arr = arr.reshape(9,1)
reshape_arr = arr.reshape(1,9)
print(reshaped_arr)
print(arr.shape)
print('*'*10)
print(reshape_arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
**********
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(3, 3)
**********
[[1 2 3 4 5 6 7 8 9]]
(3, 3)


In [20]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print('*'*10)

reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)
print(arr.shape)
print('*'*10)
reshape_arr = arr.reshape(1,6)
print(reshape_arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
**********
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
**********
[[1 2 3 4 5 6]]
(2, 3)


###3.Splitting

- vsplit

In [22]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)
print(np.vsplit(arr, 4))
print('-'*10)
print(np.vsplit(arr, 2))

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1, 2, 3, 2]]), array([[4, 5, 6, 2]]), array([[7, 8, 9, 2]]), array([[7, 8, 9, 2]])]
----------
[array([[1, 2, 3, 2],
       [4, 5, 6, 2]]), array([[7, 8, 9, 2],
       [7, 8, 9, 2]])]


- hsplit

In [23]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)
print(np.hsplit(arr, 4))
print('-'*10)
print(np.hsplit(arr, 2))

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1],
       [4],
       [7],
       [7]]), array([[2],
       [5],
       [8],
       [8]]), array([[3],
       [6],
       [9],
       [9]]), array([[2],
       [2],
       [2],
       [2]])]
----------
[array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 8]]), array([[3, 2],
       [6, 2],
       [9, 2],
       [9, 2]])]


- split

In [24]:
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)
print(np.split(arr,2,axis =1))
print('-'*10)
print(np.split(arr, 2, axis = 0))

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 8]]), array([[3, 2],
       [6, 2],
       [9, 2],
       [9, 2]])]
----------
[array([[1, 2, 3, 2],
       [4, 5, 6, 2]]), array([[7, 8, 9, 2],
       [7, 8, 9, 2]])]


###4.Merging

- concatenate

In [27]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.concatenate((arr1,arr2,arr3, arr4))

print(concat_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]


- hstack = horizantal stacking

In [29]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.hstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]


- vstack - values added vertically

In [30]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.vstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


- stack

In [31]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.stack((arr1,arr2,arr3,arr4), axis = 0)

print(concat_arr)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


In [32]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.stack((arr1,arr2,arr3,arr4), axis = 1)

print(concat_arr)

[[1 1 9 8]
 [2 5 2 2]
 [3 2 3 9]
 [4 9 5 4]]
